---
- name: Install Java 1.7
  yum: name=java-1.7.0-openjdk state=present

- name: Install the EPEL repo
  yum: name=epel-release

- name: Does Tomcat exist on server already?
  stat: path={{tc_home}}
  register: tomcat_stat

- name: Install Tomcat
  yum: name=tomcat state=latest
  when: not tomcat_stat.stat.exists

- name: Start Tomcat
  service: name=tomcat state=started enabled=yes

# - name: deploy iptables rules
  # template: src=iptables-save dest=/etc/sysconfig/iptables
  # notify: restart iptables

- name: wait for tomcat to start
  wait_for: port={{http_port}}
